# Generated by Django 2.2.6 on 2019-10-01 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
                ('friend_requests', models.ManyToManyField(related_name='_user_friend_requests_+', to='mainapp.User')),
                ('friends', models.ManyToManyField(related_name='_user_friends_+', to='mainapp.User')),
            ],
        ),
        migrations.CreateModel(
            name='CasualUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mainapp.User')),
            ],
            bases=('mainapp.user',),
        ),
        migrations.CreateModel(
            name='CommercialUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mainapp.User')),
            ],
            bases=('mainapp.user',),
        ),
        migrations.CreateModel(
            name='PremiumUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mainapp.User')),
            ],
            bases=('mainapp.user',),
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_set', to='mainapp.User')),
                ('to_friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_friend_set', to='mainapp.User')),
            ],
            options={
                'unique_together': {('to_friend', 'from_friend')},
            },
        ),
    ]
