# Generated by Django 2.2.4 on 2019-10-30 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casualuser',
            name='friend_requests',
            field=models.ManyToManyField(to='mainapp.CasualUser'),
        ),
    ]
