# Generated by Django 2.2.4 on 2019-10-29 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='messages',
        ),
        migrations.AddField(
            model_name='group',
            name='messages',
            field=models.ManyToManyField(related_name='message_on', to='mainapp.GroupMessage'),
        ),
    ]
