# Generated by Django 2.2.6 on 2019-10-02 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoneyRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
                ('from_user', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='transactions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='wallet_money',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='money_requests',
            field=models.ManyToManyField(to='mainapp.MoneyRequest'),
        ),
    ]
