# Generated by Django 2.2.4 on 2019-10-29 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20191029_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmessage',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_message', to='mainapp.CasualUser'),
        ),
        migrations.AlterField(
            model_name='premiumuser',
            name='next_payment_premium',
            field=models.DateField(auto_now_add=True),
        ),
    ]
