# Generated by Django 2.2.4 on 2019-10-29 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20191029_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
