# Generated by Django 2.2.6 on 2019-10-30 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TempUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=200)),
                ('email_reg', models.EmailField(max_length=200)),
                ('category', models.CharField(max_length=50)),
                ('dob', models.DateField()),
            ],
        ),
    ]
